apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: container workflow
on:
  push:
    branches:
      - "main"
jobs:
  Checkout:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout
  MavenBuild:
    needs: Checkout
    steps:
      - uses: docker://maven:3-eclipse-temurin-17
        shell: sh
        run: |
          mvn clean verify -Dtest="*,!MySql*,!Postgres*"
