apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: container workflow
on:
  push:
    branches:
      - "**"
jobs:
  go-build:
    steps:
      - uses: docker://golang:1.20
        kind: build
        run: echo "hello world"
        shell: sh
