apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: container workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: docker://golang:1.20
        name: Say hello
        shell: sh bash
        run: echo "hello world"
